feat:add cmd config file
emqx/neuron pull request #1431
Opened 2023-07-31 03:50 UTC by ZhouBox

2023-07-31 08:03 UTC, eeff commented on src/argparse.c
> +cfile:
also about readability, the `goto` statement combined with the `switch` statement makes the code difficult to comprehend, maybe it is better to parse the `config_file` option in a separate function, and then these `if` checks could be resided in that function ?

2023-07-31 08:15 UTC, ZhouBox commented on src/argparse.c
> +{
I think non reusable small functions actually hinder readability.

2023-07-31 09:28 UTC, eeff commented on src/argparse.c
> +    } else {
you don't need to put the main logic in the else branch since the `return` statement ends the control flow

2023-07-31 09:30 UTC, eeff commented on src/argparse.c
> +    if (config_file) {
the `neu_cli_args_init` function is getting complex, maybe we could combine these `if` statements and the ` resolve_config_file_path` function into one ?

2023-08-04 03:45 UTC, eeff requested changes

2023-08-04 03:45 UTC, eeff commented on src/argparse.c
> +    if (config_file) {
it is possible to make this function more flat:
```
if (NULL == config_file) {
  return 0;
}

if (!file_exists(config_file)) {
  return -1;
}

....
```

2023-08-04 07:29 UTC, fengzeroz approved these changes

2023-08-17 06:21 UTC, eeff approved these changes

2023-08-17 08:14 UTC, merged